// let spreadsheetId = "idOfMySheet";
// let range = "nameOfSheet!A1";
// let valueInputOption = "RAW";
// let myValue = 5;

// let values = [[myValue]];
// let resource = {
//   values,
// };
// sheets.spreadsheets.values.update(
//   {
//     spreadsheetId,
//     range,
//     valueInputOption,
//     resource,
//   },
//   (err, result) => {
//     if (err) {
//       console.log(err);
//     } else {
//       console.log("%d cells updated.", result.updatedCells);
//     }
//   }
// );

import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: "spreadsheet@spreadsheet-421011.iam.gserviceaccount.com",
  key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNpG7L7aMo5TLX\nBuzkOU4wDWuch+SYe3UInPz+AY0LTDf+C2yP4hgBysKx/Z0l1B0khSP8XrDBUtY3\nqxg+3zMaywPTyCzACuOj/5AIRPK07cdhNj8s7KsmVTszjSPwA9OA+s9s3iQNucUd\nhclAIMjes7hVWy0O6y5rlSzuml43w+wGPjgV44hwcuopSp2lP9FNi1w8LTcEt6UV\nI97YEoK2uML2708CDOY4aOIJfWYidQj4Ot5nxEMDkYWl6ieX97jJq6da1/N2r/la\nfBKBKaFh1qiq/5XqS4P4TAIqF2kCKARu7EOAhVyeW+DheC+ZArL2g//DG9RjPXyg\neMQLSbopAgMBAAECggEABM+JR1IXhO2u6bx1moVDPXDRPzhi2FZ2GcAqPA7NrWzt\n6GoXKnZfgh0SuoSefCDNihZfC+Tj7Db96VddbBI83Du5si1V7sJX67Oj/tHnq+M5\nDrlO0T3rDLLfnz87kZzxp6ttFNmhIBm3gwqOlKfgZqb0O2rst3lfot4G0AZMbaik\nB9ogekULt2qzhsSGgNybaGDJnNe0QDK2mIMWNsGISevLAWhu1zwS0zQuZPeYTIFW\nOmsJ/apYATbEiaUXG3wZCMcWzEH1sIb19hENRrrM/lL6756VkXStLX+wrB+boUpl\n5sPzn4tmuVzcXpPp/y+Rk8Hl7ufCKKxUYFdnX+QxwQKBgQDFFIAmtSgfcvTXPxwY\nyPKGni5x2XOYg5ZIdFZK4XZwnMbrUmAAlwzOq6ko8HSP6Op6HvOtX8rrUP/s6Gtw\nn99wZuWtGMvv9BwSQfF/c2Tb/H64ZeT8NXHGlPTFQqM4B/LXLoImR5BrgTSyU0mq\nY17xzXgB+Sr/20X3s2vundKg6QKBgQC3/QKBLi6cC4TWWceNkjyOLwu4CfyHyWAu\nd+yl6KLhRSo/0dLcbD8gIRzBbvLs5i+SZi3Mh/xe7BYEZogwQQCpAmT1Bzt55qYT\nZpMhzrgqhO5xjz2SJ30C4Ky+RQ4PqiR6ZAqq+VL9ax7nMrrTO6Q2jIxsG2ANgzWp\nn6FCXdSHQQKBgQCekHz/J7gtfXdjC4LWqi7/gpuJvFRWPGEY0IlxW+/IcUtWoINf\nVijWy6ShrL2L3/Fv6iFSuATyycvv15xCFE9ZB2D5oT7MRBKl2eqtCbH3kTJ/uHPB\nPFrbVJOPdqsN9M88tE3A8MlQxbcZVwupDKSiVhedNtWS3+BuiCxp4w9JqQKBgGQR\n05PpR2aOCVEAgb3pZNA8nFYb8GL2Tz7W8TqHnleB4+nUOKi0o1zZRaebrbrVs9gf\nhRdyevwx0gPQtI/yOuaxq7Ftnpa9sWRp7Op9YcOWi43uR6G/oom3I51VN8GjW7XJ\nxdeaRd4ZrjQ3bk/HZ5hXt2RxOzv+Omioru/G0vpBAoGAPxQNlgqVgT/SFZzAPQKX\nUDXgf6Sx9HQLBmxcaJ2MktpGVMVw92Mdr3+HO/wRBY9AQD9pX3VkoUmFLuGF1Ygg\nJDbfQCpRfQ7EuDkZNtJju1OKLzF8CgSRpGbzZRQvMo7HUBoxlcO9afLR2471POb7\nWmcD3YO6umsCz0cnR2l5akA=\n-----END PRIVATE KEY-----\n",
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

const doc = new GoogleSpreadsheet(
  "18_0zVG1l3-HIhPwvSuONZxqwrjOCRN2JYhiiByi06_s",
  serviceAccountAuth
);

await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);
// await doc.updateProperties({ title: "renamed doc" });

const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
console.log(sheet.title);
console.log(sheet.rowCount);

await sheet.loadCells('D7:D7'); // load only D7 cell

  const cell = sheet.getCell(6, 3); // get D7 cell, 0-based index
  cell.value = 1234; // set the value
  await sheet.saveUpdatedCells(); // save the changes



// adding / removing sheets
// const newSheet = await doc.addSheet({ title: "another sheet" });
// await newSheet.delete();
